#!/usr/bin/env php

<?php
    $composer_needle_array = [
        'init' ,
        'upgrade'
    ];

    if((!file_exists('./vendor/autoload.php') && sizeof($argv) === 1) ||
        (sizeof($argv) == 2 && in_array($argv[1] , $composer_needle_array))) {
        exec('composer install');
    }

    require 'vendor/autoload.php';

    use Illuminate\Container\Container;
    use Illuminate\Events\Dispatcher;
    use Illuminate\Console\Application;

    try {
        $container = new Container;
        $events = new Dispatcher($container);

        $artisan = new Application($container, $events, 'Version 1');
        $artisan->setName('ACID-E Console Application');

        $artisan->resolve(ACIDE\App\Commands\Init::class);
        $artisan->resolve(ACIDE\App\Commands\Drop::class);
        $artisan->resolve(ACIDE\App\Commands\Upgrade::class);

        $artisan->run();
    } catch (Exception $exception) {
        echo $exception->getMessage();
    }
?>