name: 'Packages Split'

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'morajlab.fluent-app-ui-kit'
            split_repository: 'fluent-app-ui-kit'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          package-directory: 'libs/${{ matrix.package.local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.split_repository }}'
          branch: 'master'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: 'libs/${{ matrix.package.local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.split_repository }}'
          branch: 'master'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'
